GET http://localhost:3000/product/1.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUwMTQyMDZ9._yoIQUTaUyogkbS5SwcFy8VP8lDgDNLcoDqboTklPqc

{

}

###

GET http://localhost:3000/product/2.json
Content-Type: application/json

{
  
}

###

GET http://localhost:3000/product/3.json
Content-Type: application/json

{
  
}

###

GET http://localhost:3000/products.json
Content-Type: application/json

{
  
}

###

POST http://localhost:3000/create.json
Content-Type: application/json

{
  "name": "Console", 
  "price": 500.0,
  "image_url": "",
  "description": "A ready to play machine that hooks up to a screen."
}

###
POST http://localhost:3000/create.json
Content-Type: application/json

{
  "name": "Screen", 
  "price": 100.0,
  "image_url": "",
  "description": "A visual display that can be hooked up to a machine with the proper outputs."
}

###

PATCH http://localhost:3000/patch.json
Content-Type: application/json

{
  "id": 5,
  "name": "Console", 
  "price": 450.0,
  "image_url": "",
  "description": "A ready to play machine that hooks up to a screen."
}

###

DELETE http://localhost:3000/delete/4.json

###

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "LilUziGirth",
  "email": "liluzigirth1@gmail.com",
  "password": "wilson2021",
  "password_confirmation": "wilson2021"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
POST http://localhost:3000/order/new.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNjcwNjh9.YVm3FBjQPh7mLUr9UXSSJrJfNdePr2VZRcE_Rm-0xws
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 1,
  "subtotal": 50.0,
  "tax": 5.0,
  "total": 55.0
}

###

GET http://localhost:3000/index/.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNjcwNjh9.YVm3FBjQPh7mLUr9UXSSJrJfNdePr2VZRcE_Rm-0xws
Content-Type: application/json

###

GET http://localhost:3000/index/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNjcwNjh9.YVm3FBjQPh7mLUr9UXSSJrJfNdePr2VZRcE_Rm-0xws
Content-Type: application/json

###


